### PR TITLE
feat: added time fields

### PR DESCRIPTION
**Pull request by RinkiyaKeDad**
Fix for #16 

I've added a Last Seen time field in the policy report CRD. Please let me know if this wasn't the correct way of adding this or if some other time fields are required too.

### CODE REVIEW

**Comment by JimBugwadia** [comment]
@RinkiyaKeDad - for each policy report result entry, I suggest adding:

- firstSeen
- lastSeen
- occurrences 

@ancatri @rficcaglia - any thoughts?

**Comment by sunstonesecure-robert** [comment]
I don't have a strong preference but other concepts/names for this same sort of info might be:

- start/end 
- collected/expired

not sure the "last" concept is needed insofar as if I have a collection of results, and each result has a timestamp (whether 1 or a pair) then code can determine "first" from "last" sorting without having to burden the code producing the result with that logic.  for example in some corner case where the process takes variable time, I might have the "last" scan/assessment/rule fire "last" but the result come before the previous one.  so I might have 2 results:

# result 1
start: T0
end: T3

# result 2
start: T1
end: T2

where T0 < T1 < T2 < T3

**Comment by ancatri** [comment]
Following the Oscal terminology , we have multiple objects where timestamps are present as follows:
- Assessment Result -> Observation   //Describes an individual observation FOR EACH goal, CIS-benchmark, rule, gate, check, FOR EACH component instance in the env or inventory ; We have a _**timestamp**_ for each observation , eg in case of kube bench xxdf , we copy the **_timestamp_** value at the rule check by open_scap 

- Assessment Result -> Finding // Describes an individual finding FOR EACH control or control part (or statement) of the group considered ; We aggregate at this level the summary of the observations . eg count fail, count pass etc. We have the 
**_collected_** time and **_expiration_** time for each finding , eg for the kube bench xxdf, **_collected_** is the time we fetch the results xml from the cluster config maps  and the **_expire_** is the time of the next scheduled open scap scan.

- Assessment Result -> Result // Identifies all of the assessment observations and findings based on an Assessment Plan scope; We have **_start_**: dateTime-with-timezone and **_end_**: dateTime-with-timezone , where **_start_** and **_end_** are the audit interval defined in the Assessment Plan

**Comment by ancatri** [comment]
I agree, sunstonesecure-robert, first_seen and last_seen can be calculated , they are time series properties, they are not primary properties like **_timestamp_** or **_collected_** or **_expired_** and they are not secondary properties either like **_interval_** which can be calculated from **_end_** - **_start_** properties within one given Result object.

Depending on the importance of the secondary properties, we may add them or not to the Result schema.
For instance, summary count_fail, count_pass etc can also be calculated, they are secondary properties calculated from the observations results fail or pass properties within one given Result object. I see they appear in the Result schema.

However,  first_seen and last_seen are time series properties, meaning we need Result objets series set to calculate them across the set; we cannot calculate them within the context of the properties of one given Result object. 

Will the series be available in our cluster context 
OR
the series will be available only on other system(s) collecting and storing them?

**Comment by RinkiyaKeDad** [comment]
> Will the series be available in our cluster context
> OR
> the series will be available only on other system(s) collecting and storing them?

Hi @ancatri! Thanks for the detailed explanation. If I am not mistaken I think we are storing all the Policy reports in the [Policy Report List](https://github.com/kubernetes-sigs/wg-policy-prototypes/blob/master/policy-report/api/v1alpha1/policyreport_types.go#L149), so we would be able to calculate first_seen and last_seen from the timestamp of each policy report. @JimBugwadia please correct me if I'm wrong in understanding this.

**Comment by JimBugwadia** [comment]
@RinkiyaKeDad lets simplify this to store `timestamp` for each result.

**Comment by RinkiyaKeDad** [comment]
@JimBugwadia - changed lastSeen to Timestamp please take a look. Running the `make` command to regenerate the YAMLs made a lot of changes, were these expected?

**Pull request closed without merging**
