### PR TITLE
Added fields fix#15

### PR DESCRIPTION
**Pull request by phoenixking25**
fix https://github.com/kubernetes-sigs/wg-policy-prototypes/issues/15

### CODE REVIEW

**Comment by JimBugwadia** [comment]
@phoenixking25 - thanks for the submission. However, we need to decide if these fields are required in the results or should be handled by an upstream system.

@ancatri @rficcaglia - any thoughts?

**Comment by sunstonesecure-robert** [comment]
no strong opinions here just observing that these are very nuanced (english) terms vs something perhaps more univeral/tranlatable/adaptable like:

## rationale

- description
- purpose
- origin
- statement

or more precise in the domain:

- control
- objective
- implementation

## remediation

admittedly this is more difficult to unpack without imbuing lots of specific domain meaning...

- goal
- suggestion
- requirement
- task

or more precise in the domain:

- attestation
- evidence

I do wonder if remediation info belongs in the schema.  It seems so open to interpretation that it might best belong in the code using the report data rather than be generated as part of the result?

**Comment by JimBugwadia** [comment]
@phoenixking25 thanks for this PR, but on further discussion with the team it was decided that these fields are not needed. So closing this PR.

**Pull request closed without merging**
