### PR TITLE
Create sample_compliance_operator_result.json

### PR DESCRIPTION
**Pull request by ancatri**
OSCAL based policy validation result sample.

### CODE REVIEW

**Comment by ancatri** [comment]
ancatri got CLA

**Comment by JAORMX** [comment]
@ancatri could you give a bit more context on how this was generated?

**Comment by ancatri** [comment]
> @ancatri could you give a bit more context on how this was generated?

@JAORMX The schema was created manually as a subset of OSCAL Assessment Result. The actual Compliance Operator xccdf translation into OSCAL Assessment Result is part of the https://auditree.github.io open source project.

**Comment by sunstonesecure-robert** [comment]
so if I understand - having read [the google doc as intro](https://docs.google.com/document/d/1RdxSz5kEdOPWPVCRNXWBM3AmeU2iBxRAKe89hN3JrtE/edit#) - would this be embedded into a PR as json in the results array?  I think that's the goal but wasn't clear.

**Comment by rficcaglia** [comment]
@JimBugwadia maybe this should go into a test fixture directory?

**Comment by JimBugwadia** [comment]
@ancatri - the samples folder is for Policy Report CRD samples. If you wish, perhaps we can create another folder to store an OSCAL sample? If so, please submit a new PR.

**Pull request closed without merging**
