### PR TITLE
Update wgpolicyk8s.io/v1alpha1 API schema objects terminology per alignment w/ OSCAL

### PR DESCRIPTION
**Pull request by ancatri**
Update of the current wgpolicyk8s.io/v1alpha1 API schema objects terminology following the OSCAL (v1.0) Assessment Result schema objects terminology

### CODE REVIEW

**Comment by RinkiyaKeDad** [comment]
Should I make these changes in the [policyreport_types.go](https://github.com/kubernetes-sigs/wg-policy-prototypes/blob/master/policy-report/api/v1alpha1/policyreport_types.go) file so that the API Reference is automatically generated?

**Comment by rficcaglia** [comment]
>  so that the API Reference is automatically generated?

@JimBugwadia yes, isn't this the preference?

**Comment by JimBugwadia** [comment]
I've made the schema updates in this PR:

https://github.com/kubernetes-sigs/wg-policy-prototypes/pull/39

It needs to be approved and merged. We are currently blocked as we do not have any other active approvers. I am trying to get that sorted.

**Comment by JimBugwadia** [comment]
Closing this PR. The changes need to be made to the Golang structs and are captured in this PR:

https://github.com/kubernetes-sigs/wg-policy-prototypes/pull/39

**Pull request closed without merging**
